/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 heart_in_love_gtlf.glb 
*/

import React, { useRef } from "react";
import { useGLTF, useTexture, Float } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const Heart = ({ ...props }) => {
  const ref = useRef();
  useFrame((state, delta) => (ref.current.rotation.x += delta));
  const { nodes, materials } = useGLTF("model/heart_in_love_gtlf.glb");
  const texture = useTexture("texture/glory-me.png");
  return (
    <Float floatIntensity={3}>
      <group {...props} dispose={null}>
        <mesh
          ref={ref}
          geometry={nodes.Heart.geometry}
          material={materials.Heart}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <meshMatcapMaterial map={texture} />
        <mesh geometry={nodes.Marble.geometry} material={materials.Marble} />
      </group>
    </Float>
  );
};

useGLTF.preload("/heart_in_love_gtlf.glb");
export default Heart;
